/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.variables_ejercicio1;

public class App {
    public static void main(String[] args) {
        int x = 200;
        int y = 111;
        System.out.println(x);
        System.out.println(y);
        System.out.println(x + y);
        System.out.println(x - y);
        System.out.println(x * y);
        System.out.println(x / y);
    }
}
