/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_1;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);
        
        System.out.print("Introduce una hora: ");
        int horas = myScanner.nextInt();
        
        if ( horas >= 6  && horas <= 12) {
            System.out.println("Buenos dias");
        }
        else if (horas >= 13 && horas <= 20) {
            System.out.println("Buenas tardes");
        }
        else {
            System.out.println("Buenas noches");
        }
    }
}
