/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio4;

public class App {
    public static void main(String[] args) {
        String nombre;
        String direccion;
        String telefono;
        
        nombre = "Juan Fran";
        direccion = "Mountain View, California, United States";
        telefono = " 800900549";
        
        System.out.println(nombre);
        System.out.println(direccion);
        System.out.println(telefono);
    }
}
