/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_4;

import java.util.Arrays;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String nota;
        Scanner scanner = new Scanner(System.in);
        
        System.out.print("Introduce 3 notas: ");
        int[] numeros = {scanner.nextInt(), scanner.nextInt(), scanner.nextInt()};

        int media = Arrays.stream(numeros).sum() / numeros.length;
        
        if (media < 5) {
            nota = "Insuficiente";
        } else if (media > 5 && media < 6) {
            nota = "Suficiente";
        } else if (media >= 6 && media < 7) {
            nota = "Bien";
        } else if (media >= 7 && media <= 8.5) {
            nota = "Notable";
        } else {
            nota = "Sobresaliente";
        }
        
        
        System.out.printf("Tu nota es %d, %s.", media, nota);
    }
}
