/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio3;

public class App {
    public static void main(String[] args) {
        String nombre;
        
        nombre = "Juan Fran";
        
        System.out.println(nombre);
        
    }
}
