/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_5;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        
        System.out.print("Introduce 3 numeros: ");
        int[] numeros = {scanner.nextInt(), scanner.nextInt(), scanner.nextInt()};
        
        if (numeros[0] > numeros[1] && numeros[0] > numeros[2]) {
            if (numeros[1] > numeros[2]) {
                System.out.printf("%d, %d, %d\n", numeros[2], numeros[1], numeros[0]);
            } else {
                System.out.printf("%d, %d, %d\n", numeros[1], numeros[2], numeros[0]);
            }
        } else if (numeros[1] > numeros[2]) {
            if (numeros[0] > numeros[2]) {
                System.out.printf("%d, %d, %d\n", numeros[2], numeros[0], numeros[1]);
            } else {
                System.out.printf("%d, %d, %d\n", numeros[0], numeros[2], numeros[1]);
            }
        } else {
            if (numeros[0] > numeros[1]) {
                System.out.printf("%d, %d, %d\n", numeros[1], numeros[0], numeros[2]);
            } else {
                System.out.printf("%d, %d, %d\n", numeros[0], numeros[1], numeros[2]);
            }
        }
    }
}
