/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_2;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner myScanner = new Scanner(System.in);
        
        System.out.print("Escribe un dia de la semana entre 1 y 7: ");
        int nDia = myScanner.nextInt();
        String  dia = ""; 
        
        if(nDia == 1) {
            dia = "Lunes";
        }
        else if (nDia == 2) {
            dia = "Martes";
        }
        else if (nDia == 3) {
            dia = "Miercoles";
        }
        else if (nDia == 4) {
            dia = "Jueves";
        }
        else if (nDia == 5) {
            dia = "Viernes";
        }
        else if (nDia == 6) {
            dia = "Sabado";
        }
        else if (nDia == 7) {
            dia = "Domingo";
        }
        else {
            dia = "Error";
        }
        
        System.out.println(dia);
    }
}
